name: compiler-build

on: [push, pull_request]

jobs:
  test:
    needs: [build-compiler]
    name: test-${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        dotnet-version: ['6.0']
        config:
          - {name: x86_64-macos, os: macos-latest, shell: bash}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Packages
        run: pip install -r requirements.txt

      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          pytest
